### ISSUE TITLE
define output filename bug

### ISSUE THREAD

**Issue by pauls86** [torvista/Zen_Cart-Google_Merchant_Center_Feeder#4]
entered setting as crazy1 for output file however i instead get crazy1_products_en_1-212.xml
google cant find the file although yesterday it was working only difference is i added more items and generated a new feed file.
went from 138 items to 212 and file name was originally generating as crazy1_products_en_1-138.xml
takes ages to get google to recognise a file so this is inconvenient as having to keep trying to link to file and upload but getting emails from google saying it basically wasn't expecting that file matching the filename i've set in google

**Comment by torvista** [comment]
The issue of naming, with regards to offsets and limits was unresolved, I've changed it to use the same filename for now.
