### ISSUE TITLE
php 7.3

### ISSUE THREAD

**Issue by wiztechinc** [torvista/Zen_Cart-Google_Merchant_Center_Feeder#5]
apologies - thought I was testing a site with this version and turns out it wasn't - so the warnings are the apostrophes only
get this warning when I run it:
PHP Warning: preg_split(): No ending delimiter ',' found in /googlefroogle.php on line 147.

**Comment by torvista** [comment]
So there is no problem with the version here?

**Comment by wiztechinc** [comment]
Sorry, should have been more specific - lines 228 - 231 all need quotes around GOOGLE_PRODUCTS_FEED_SORT

**Comment by torvista** [comment]
https://github.com/torvista/Zen_Cart-Google_Merchant_Center_Feeder/blob/559bf723d92c61baf156c8c234aa04e39dca1152/catalog/admin/googlefroogle.php#L228-L231

I don't see why they need quotes.
228 is to display the text
229-231 are tests for true, to pre-select the correct radio.

**Comment by wiztechinc** [comment]
It creates a warning log file for future versions. Which I have deleted without copying.

**Comment by torvista** [comment]
My dev site is php 8.0.8, with strict reporting and declare(strict_types=1) in the file, and I can get no errors.
If you put quotes around the uses, they will become literal text instead of constants.

**Comment by wiztechinc** [comment]
But on 7.3, they create error logs. And now they show in admin, freaking out my client. Any advice?

**Comment by torvista** [comment]
Post a screen shot of the error, and the debug text and the snippet of code.
