### ISSUE TITLE
need sprintf here...

### ISSUE THREAD

**Issue by proseLA** [torvista/Zen_Cart-Google_Merchant_Center_Feeder#6]
https://github.com/torvista/Zen_Cart-Google_Merchant_Center_Feeder/blob/8c7b87ed77a9e2573dfe81d64b88c629581da368/catalog/googlefroogle.php#L137
```
<p><?= sprintf(TEXT_GOOGLE_PRODUCTS_STARTED, $google_base->google_base_version()); ?></p>
```

**Comment by proseLA** [comment]
my mistake.  sorry.

**Comment by proseLA** [comment]
so i was running into the dreaded memory exhaustion, and decided to merge your code into mine...  or my code into yours...  and the work done here with regards to the memory exhaustion has resolved my error.  so thank you for that!  good job on this.

**Comment by torvista** [comment]
Thank goodness for that! When a dusty thing like this rears its ugly head I see my spare time disappear!
My work on this was little more than splints to keep it hobbling along.
